# Generated by Django 2.2.16 on 2020-09-18 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='media/profile_image', verbose_name='Fotoğraf')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Adı')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Soyadı')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-Posta')),
                ('phone', models.CharField(default=0, max_length=11, verbose_name='Telefon Numarası')),
                ('parent_phone', models.CharField(default=0, max_length=11, verbose_name='Veli Telefon Numarası')),
                ('gender', models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=30, null=True, verbose_name='Cinsiyet')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Kullanıcı Adı')),
            ],
        ),
    ]
