# Generated by Django 2.2.16 on 2020-09-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='authority',
        ),
    ]
